Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-24.04"

  # Load Balancer
  config.vm.define "lb1" do |lb|
    lb.vm.hostname = "lb1"
    lb.vm.network "private_network", ip: "192.168.56.10"
    lb.vm.provider "vmware_desktop" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end

  # 3 Master Nodes
  (1..3).each do |i|
    config.vm.define "master#{i}" do |master|
      master.vm.hostname = "master#{i}"
      master.vm.network "private_network", ip: "192.168.56.#{10+i}"
      master.vm.provider "vmware_desktop" do |v|
        v.memory = 8192
        v.cpus = 4
      end
    end
  end

  # 3 Worker Nodes
  (1..3).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.hostname = "worker#{i}"
      worker.vm.network "private_network", ip: "192.168.56.#{20+i}"
      worker.vm.provider "vmware_desktop" do |v|
        v.memory = 12288
        v.cpus = 8
      end
    end
  end

  # NFS Server
  config.vm.define "nfs" do |nfs|
    nfs.vm.hostname = "nfs"
    nfs.vm.network "private_network", ip: "192.168.56.40"
    nfs.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

  # Vault Server
  config.vm.define "vault" do |vault|
    vault.vm.hostname = "vault"
    vault.vm.network "private_network", ip: "192.168.56.50"
    vault.vm.provider "vmware_desktop" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

end