---
- name: External Secrets Operator Setup
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Create external-secrets namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: external-secrets
        state: present

    - name: Deploy External Secrets Operator (using official manifest)
      kubernetes.core.k8s:
        state: present
        src: https://github.com/external-secrets/external-secrets/releases/download/v0.9.19/install-bundle.yaml
