---
- name: NFS Subdir External Provisioner Setup
  hosts: k8s_cluster
  become: yes
  tasks:
    - name: Create nfs-provisioner namespace
      kubernetes.core.k8s:
        api_version: v1
        kind: Namespace
        name: nfs-provisioner
        state: present

    - name: Deploy NFS Subdir External Provisioner
      kubernetes.core.k8s:
        state: present
        src: https://raw.githubusercontent.com/kubernetes-sigs/nfs-subdir-external-provisioner/v4.0.2/deploy/kubernetes/deployment.yaml

    - name: Patch deployment to use NFS server VM
      kubernetes.core.k8s:
        kind: Deployment
        namespace: nfs-provisioner
        name: nfs-subdir-external-provisioner
        merge_type: strategic-merge
        definition:
          spec:
            template:
              spec:
                containers:
                  - name: nfs-subdir-external-provisioner
                    env:
                      - name: NFS_SERVER
                        value: "172.18.8.102"
                      - name: NFS_PATH
                        value: "/srv/nfs/k8s"
