---
- name: NFS Server Setup
  hosts: nfs
  become: yes
  tasks:
    - name: Install NFS server packages
      apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create export directory
      file:
        path: /srv/nfs/k8s
        state: directory
        owner: nobody
        group: nogroup
        mode: '0777'

    - name: Configure NFS export
      lineinfile:
        path: /etc/exports
        line: '/srv/nfs/k8s *(rw,sync,no_subtree_check,no_root_squash)'
        create: yes

    - name: Export NFS shares
      command: exportfs -ra

    - name: Ensure NFS server is running
      service:
        name: nfs-kernel-server
        state: started
        enabled: yes
